/**
 * FuelRouteOS — Branding Helpers
 * Always import from config/tenantBranding for all tenant-specific values.
 * Do NOT hardcode company names, phones, or emails anywhere else.
 */
import { tenantBranding } from "@/config/tenantBranding";

export const getTenantName = () =>
  tenantBranding.companyDisplayName || "FuelRouteOS";

export const getTenantLegalName = () =>
  tenantBranding.companyLegalName || getTenantName();

export const getTenantLogo = () => tenantBranding.logoUrl || null;

export const getTenantInitials = () => {
  const name = tenantBranding.companyDisplayName || "FR";
  const words = name.trim().split(" ").filter(Boolean);
  if (words.length === 1) return words[0].slice(0, 2).toUpperCase();
  return (words[0][0] + words[words.length - 1][0]).toUpperCase();
};

export const getTenantAccentColor = () =>
  tenantBranding.accentColor || "#2563EB";

export const getDispatchPhone = () => tenantBranding.dispatchPhone || null;

export const getSupportPhone = () => tenantBranding.supportPhone || null;

export const getSupportEmail = () => tenantBranding.supportEmail || null;

export const getBillingEmail = () => tenantBranding.billingEmail || null;

export const getPoweredByLine = () =>
  `Powered by ${tenantBranding.poweredBy || "Sentinels FleetOps"}`;

export const getPlatformName = () => tenantBranding.platformName || "FuelRouteOS";

export const getPlatformProductName = () =>
  tenantBranding.platformProductName || "FuelRouteOS Driver";

export const getDocumentHeaderData = () => ({
  companyName: getTenantName(),
  logoUrl: getTenantLogo(),
  initials: getTenantInitials(),
  platformName: getPlatformName(),
  poweredBy: getPoweredByLine(),
  showLogo: tenantBranding.documentBranding?.showLogo ?? true,
});

export const getDocumentFooterData = () => ({
  footerText: tenantBranding.documentBranding?.footerText || "Generated by FuelRouteOS",
  receiptFooter: tenantBranding.documentBranding?.receiptFooter || "",
  reportFooter: tenantBranding.documentBranding?.reportFooter || "",
  showPoweredBy: tenantBranding.documentBranding?.showPoweredBy ?? true,
  poweredBy: getPoweredByLine(),
  supportPhone: getSupportPhone(),
  supportEmail: getSupportEmail(),
});

/**
 * getNavigationAddress(job)
 * Returns the clean navigation-ready address string for a job's delivery site.
 * Use this for ALL Open in Maps, Start Navigation, and Copy Address actions.
 */
export function getNavigationAddress(job) {
  return job?.site?.address || null;
}