export const driver = {
  id: "DRV-001",
  name: "Quincy Micheaux",
  email: "driver@fuelrouteos.demo",
  phone: "+1 (832) 755-6477",
  company: "Sentinels FleetOps Demo Carrier",
  cdl: "TX-CDL-88421",
  initials: "QM",
};

export const truck = {
  id: "TRK-4821",
  number: "4821",
  make: "Peterbilt",
  model: "567",
  year: 2023,
  vin: "1XPBD49X1PD000001",
  licensePlate: "TX-FLT-482",
  odometerMi: 84320,
  lastInspection: "2026-04-28",
};

export const trailer = {
  id: "TRL-7733",
  number: "7733",
  type: "MC-331 Tanker",
  capacity: 9200,
  compartments: [
    { id: 1, capacity: 3000, product: "100*DIESEL-OFFROAD RED",  loadedGallons: 2980, color: "#ef4444" },
    { id: 2, capacity: 3200, product: "100*DIESEL-ONROAD CLEAR", loadedGallons: 3180, color: "#3b82f6" },
    { id: 3, capacity: 2000, product: "100*GAS 87 REG OCTANE",   loadedGallons: 1990, color: "#f59e0b" },
    { id: 4, capacity: 1000, product: "100-DEF-NOXGUARD-GAL",   loadedGallons: 510,  color: "#a855f7" },
  ],
};

export const route = {
  id: "RTE-20260505-01",
  date: "2026-05-05",
  driverId: "DRV-001",
  truckId: "TRK-4821",
  trailerId: "TRL-7733",
  totalStops: 6,
  completedStops: 0,
  status: "active",
  estimatedMiles: 142,
  estimatedDuration: "6h 30m",
};

export const products = [
  "100*DIESEL-OFFROAD RED",
  "100*DIESEL-ONROAD CLEAR",
  "100*DIESEL-ONROAD CLR-BIO20",
  "100*GAS 87 REG NE OCTANE",
  "100*GAS 87 REG OCTANE",
  "100*GAS 89 MID OCTANE",
  "100*GAS 90 PREM NON ETHANOL",
  "100*GAS 92/93 PREM OCTANE",
  "100*NT DIESEL-OFFROAD RED #2s15",
  "100*R99 DIESEL-RENEWABLE CLEAR",
  "100*R99 DIESEL-RENEWABLE RED",
  "100-ADD-BIOBOR-BOTTLE",
  "100-ADD-BIOBOR-EA",
  "100-AF-FNCR5050FNAB3-CASE",
  "100-AF-MOF5050HDRED-GAL",
  "100-ATF-MOFDEXRON3-BULK",
  "100-CL-CELL30ABSORBENT",
  "100-CL-ISOPARMFLUID",
  "100-CL-KEROSENE-GAL",
  "100-CL-PEAKWINDSHIELD-CASE",
  "100-CL-SPILLPADS",
  "100-CL-VARSOL-DRUM",
  "100-DEF-BLUEPEAK-EACH",
  "100-DEF-NOXGUARD-CASE",
  "100-DEF-NOXGUARD-GAL",
  "100-DVTRN-MOFSAE10WT04-DRUM",
  "100-EQ-1\"BALLVALVE",
  "100-EQ-275TOTE-LUBES",
  "100-EQ-330TOTE-DEF",
  "100-EQ-55DRUM-DEF",
  "100-EQ-BERM",
  "100-EQ-DRUM CLOSEDTOP",
  "100-EQ-FR152HANDPUMP",
  "100-EQ-FR4210PUMP",
  "120*DIESEL-ONROAD CLEAR",
  "120*GAS 87 REG OCTANE",
  "120*GAS 89 MID OCTANE",
  "120*GAS 90 REG NE OCTANE",
  "120*GAS 92/93 PREM OCTANE",
  "120*GAS E-85 OCTANE",
  "120*NT DIESEL-OFFROAD RED #2s15",
  "130*DIESEL-OFFROAD RED",
  "130*DIESEL-ONROAD CLEAR",
  "130*GAS 87 REG OCTANE",
  "200*DIESEL-OFFROAD RED",
  "200*DIESEL-ONROAD CLEAR",
  "200*GAS 87 REG OCTANE",
];

export const customers = [
  { id: "C001", name: "Adkisson GC Partners, LLC.", erpId: "80002544-1731357929", creditChecked: true },
  { id: "C002", name: "Aqua Matrix Inc.", erpId: "8000246F-1727734031", creditChecked: true },
  { id: "C003", name: "Belfor - 1044 Tampa", erpId: "80002471-1727744416", creditChecked: true },
  { id: "C004", name: "FEC Future Contractors & Engineers Inc.", erpId: "8000253E-1731096019", creditChecked: false },
  { id: "C005", name: "In & Out Excavation LLC.", erpId: "80002536-1730988584", creditChecked: false },
  { id: "C006", name: "ION Facility Services", erpId: "80002546-1731425111", creditChecked: false },
  { id: "C007", name: "Puyenpa Construction LLC.", erpId: "80002540-1731184129", creditChecked: true },
  { id: "C008", name: "RCITX, LLC", erpId: "8000253A-1731003963", creditChecked: false },
  { id: "C009", name: "Swan Lake Rental", erpId: "80002539-1730993087", creditChecked: true },
  { id: "C010", name: "Tejas Destructors LLC.", erpId: "80002538-1730991594", creditChecked: true },
  { id: "C011", name: "The Texas Loo", erpId: "80002541-1731293077", creditChecked: true },
  { id: "C012", name: "United Rentals, Inc.:United Rentals - 673", erpId: "", creditChecked: true },
  { id: "C013", name: "AD Construction & Development Inc.", erpId: "", creditChecked: true },
  { id: "C014", name: "AR Mays", erpId: "", creditChecked: true },
  { id: "C015", name: "American Pipe & Vessel", erpId: "", creditChecked: true },
];

export const terminals = [
  { id: "T001", name: "Flint Hills Resources - Waco", erpId: "T-74-TX2707", suppliers: "Sentinels Supplier" },
  { id: "T002", name: "U.S. Oil - Bryan Finfeather", erpId: "T-74-TX-2713", suppliers: "US Oil, EXXON" },
  { id: "T003", name: "Magellan Pipeline Company, L.P. Houston", erpId: "T-76-TX-2831", suppliers: "Atlas Oil Co, Bunker One, Musket, SC Fuels, Sunoco, Valero, Motiva, Exx..." },
  { id: "T004", name: "Motiva Enterprises LLC-pasadena", erpId: "T-76-TX-2782", suppliers: "Atlas Oil Co, Musket, Wallis Oil, Motiva" },
  { id: "T005", name: "ExxonMobil Oil Corp.", erpId: "T-76-TX-2808", suppliers: "ExxonMobil, EXXON" },
  { id: "T006", name: "NuStar Logistics, L.P.- Laredo, TX", erpId: "T-74-TX-2715", suppliers: "Valero, Valero Marketing, Valero Marketing & Supply" },
  { id: "T007", name: "Phillip 66 Pasadena Terminal", erpId: "", suppliers: "Sentinels Supplier" },
  { id: "T008", name: "Flint Hills Resources Fort Worth", erpId: "T-75-TX-2664", suppliers: "Sentinels Supplier" },
  { id: "T009", name: "CITGO - Lake Charles", erpId: "T-72-LA-2368", suppliers: "Citgo, Fuel Masters LLC" },
  { id: "T010", name: "Gulf Coast Energy LLC", erpId: "T-76-TX-2790", suppliers: "Gulf Coast, EXXON / GULF COAST" },
];

export const assetTypes = ["tank", "vehicle", "generator", "equipment"];

export const jobs = [
  {
    id: "JOB-5001",
    stopNumber: 1,
    stopName: "5859 Houston",
    orderNumber: "#3977444",
    plannedTime: "06:00",
    status: "pending",
    priority: "high",
    starred: true,
    type: "D",
    weatherSensitive: false,
    customer: {
      name: "Nardone Electrical Corp",
      contact: "Frank",
      phone: "936-689-9103",
    },
    site: {
      name: "5859 Houston",
      address: "5859 Houston TX FDC BDC 400 Porter Road, Conroe, TX, 77301",
    },
    instructions: "**need a key to unlock the gen**\nDelivery on 4/29 ONLY, est 1000 gallons off-road dyed diesel, please fill to 90%\nPOC: Frank 936-689-9103",
    poNumber: "PO#91042",
    carrierNumber: "-",
    lastDelivery: "Oct 09",
    products: [
      { name: "100*DIESEL-OFFROAD RED", quantity: 1000, color: "#ef4444", assets: [{ name: "Customer Gen", qty: 1000 }] },
    ],
  },
  {
    id: "JOB-5002",
    stopNumber: 2,
    stopName: "Aldine Westfield",
    orderNumber: "#4035557",
    plannedTime: "07:25",
    status: "pending",
    priority: "normal",
    starred: false,
    type: "D",
    weatherSensitive: false,
    customer: {
      name: "Texas Johns, LLC.",
      contact: "Ruben",
      phone: "832-458-6070",
    },
    site: {
      name: "Aldine Westfield",
      address: "16207 Aldine Westfield, Houston, TX, 77032",
    },
    instructions: "NO DELIVERY ON WEEKENDS.\nPOC: Ruben: 832-458-6070 2nd poc: josh 940-337-1195",
    poNumber: "Hou-Josh",
    carrierNumber: "-",
    lastDelivery: null,
    products: [
      { name: "100*DIESEL-ONROAD CLEAR", quantity: 1300, color: "#3b82f6", assets: [{ name: "MS-1300-SV-1", qty: 1300 }] },
    ],
  },
  {
    id: "JOB-5003",
    stopNumber: 3,
    stopName: "Spring Branch",
    orderNumber: "#4035620",
    plannedTime: "07:37",
    status: "pending",
    priority: "normal",
    starred: false,
    type: "D",
    weatherSensitive: true,
    customer: {
      name: "Spring Branch Industrial",
      contact: "Andrew Perry",
      phone: "713-555-0199",
    },
    site: {
      name: "Spring Branch",
      address: "8811 Long Point Rd, Houston, TX, 77055",
    },
    instructions: "*****DO NOT FILL MS-1154 PER ANDREW PERRY*****",
    poNumber: "1018",
    carrierNumber: "-",
    lastDelivery: null,
    products: [
      { name: "100*DIESEL-OFFROAD RED", quantity: 1200, color: "#ef4444", assets: [{ name: "MS-1200-RED", qty: 1200 }] },
    ],
  },
  {
    id: "JOB-5004",
    stopNumber: 4,
    stopName: "Junction Fairbanks",
    orderNumber: "#4035635",
    plannedTime: "07:39",
    status: "pending",
    priority: "normal",
    starred: false,
    type: "D",
    weatherSensitive: false,
    customer: {
      name: "Curry Equipment Rentals & Excavation LLC",
      contact: "Eddy Welch",
      phone: "832-226-8860",
    },
    site: {
      name: "Junction Fairbanks",
      address: "Junction Fairbanks Prairie Dr & Old County Lane 29.905972, -95.530333, Houston, TX, 77064",
    },
    instructions: "*JOB SHEET REQUIRED*\nPOC: Eddy Welch 832-226-8860",
    poNumber: null,
    carrierNumber: null,
    lastDelivery: null,
    products: [
      { name: "100*DIESEL-OFFROAD RED", quantity: 1500, color: "#ef4444", assets: [{ name: "JF-Tank-01", qty: 1500 }] },
    ],
  },
  {
    id: "JOB-5005",
    stopNumber: 5,
    stopName: "Honea Egypt Rd",
    orderNumber: "#4037689",
    plannedTime: "07:51",
    status: "pending",
    priority: "normal",
    starred: true,
    type: "D",
    weatherSensitive: false,
    customer: {
      name: "Unspeakable Media LLC.",
      contact: "ORB",
      phone: "281-555-0101",
    },
    site: {
      name: "Honea Egypt Rd",
      address: "5450 Honea Egypt Rd., Montgomery, TX, 77316",
    },
    instructions: "ORB - PARMIS - EMAIL\n***AM DELIVERY***",
    poNumber: null,
    carrierNumber: null,
    lastDelivery: null,
    products: [
      { name: "100*GAS 87 REG OCTANE", quantity: 100, color: "#f59e0b", assets: [{ name: "Gen-01", qty: 100 }] },
    ],
  },
  {
    id: "JOB-5006",
    stopNumber: 6,
    stopName: "Intercontinental",
    orderNumber: "#4035763",
    plannedTime: "08:00",
    status: "pending",
    priority: "normal",
    starred: false,
    type: "D",
    weatherSensitive: false,
    customer: {
      name: "Empire Parking Area Maintenance",
      contact: "JULIO",
      phone: "281-809-6106",
    },
    site: {
      name: "Intercontinental",
      address: "18520 Intercontinental Crossing, Houston, TX, 77073",
    },
    instructions: "DELIVERY TIME ONLY 8AM-4PM\nJULIO--- 281-809-6106",
    poNumber: null,
    carrierNumber: null,
    lastDelivery: null,
    products: [
      { name: "100*GAS 87 REG OCTANE", quantity: 1000, color: "#f59e0b", assets: [{ name: "MS-1500-SV-1", qty: 1000 }] },
    ],
  },
];

export const syncItems = [
  { id: "SYN-001", jobId: "JOB-5001", type: "delivery_record", label: "Delivery Record", status: "synced", timestamp: "07:05", size: "12 KB" },
  { id: "SYN-002", jobId: "JOB-5001", type: "bol_photo", label: "BOL Photo", status: "synced", timestamp: "07:06", size: "1.8 MB" },
  { id: "SYN-003", jobId: "JOB-5001", type: "pod_signature", label: "POD Signature", status: "pending", timestamp: "07:06", size: "48 KB" },
  { id: "SYN-004", jobId: "JOB-5002", type: "arrival_check", label: "Arrival Check-in", status: "failed", timestamp: "08:12", size: "4 KB", error: "Network timeout — retry when online" },
];

export const dispatchMessages = [
  {
    id: "MSG-001",
    role: "dispatch",
    senderName: "Dispatch",
    text: "Good morning. JOB-5001 is priority — customer running low. Please head there first.",
    timestamp: "05:45",
    read: true,
    jobId: null,
    urgent: false,
  },
  {
    id: "MSG-002",
    role: "driver",
    senderName: "You",
    text: "Copy that. En route to 5859 Houston now.",
    timestamp: "05:47",
    read: true,
    jobId: "JOB-5001",
    urgent: false,
  },
  {
    id: "MSG-003",
    role: "dispatch",
    senderName: "Dispatch",
    text: "⚠️ URGENT: Spring Branch site has weather delay. Hold until further notice.",
    timestamp: "06:55",
    read: false,
    jobId: "JOB-5003",
    urgent: true,
  },
];

export const preTripChecklist = [
  { id: "pt-01", category: "Engine", label: "Engine oil level — check dipstick" },
  { id: "pt-02", category: "Engine", label: "Coolant level — check reservoir" },
  { id: "pt-03", category: "Engine", label: "No warning lights on dash" },
  { id: "pt-04", category: "Tires", label: "All tires inflated and no visible damage" },
  { id: "pt-05", category: "Tires", label: "Lug nuts secure — visual check" },
  { id: "pt-06", category: "Lights", label: "Headlights and taillights working" },
  { id: "pt-07", category: "Lights", label: "Turn signals and hazard lights working" },
  { id: "pt-08", category: "Trailer", label: "Trailer coupling secure and safety chains attached" },
  { id: "pt-09", category: "Trailer", label: "Trailer lights connected and tested" },
  { id: "pt-10", category: "Trailer", label: "All valves closed and locked" },
  { id: "pt-11", category: "Safety", label: "Fire extinguisher charged and accessible" },
  { id: "pt-12", category: "Safety", label: "Spill kit stocked and accessible" },
  { id: "pt-13", category: "Safety", label: "DOT placards correct for loaded product(s)" },
  { id: "pt-14", category: "Cab", label: "Seatbelt functional" },
  { id: "pt-15", category: "Cab", label: "Mirrors adjusted and clean" },
];

export const postTripChecklist = [
  { id: "post-01", category: "Trailer", label: "All product valves closed and capped" },
  { id: "post-02", category: "Trailer", label: "Hoses stowed and secured" },
  { id: "post-03", category: "Trailer", label: "No leaks or drips visible under trailer" },
  { id: "post-04", category: "Engine", label: "Engine off and keys turned in" },
  { id: "post-05", category: "Tires", label: "Tires inspected post-route" },
  { id: "post-06", category: "Cab", label: "Cab cleaned, trash removed" },
  { id: "post-07", category: "Safety", label: "Spill kit restocked if used" },
  { id: "post-08", category: "Paperwork", label: "BOL copies returned to dispatch" },
];

export const maintenanceHistory = [
  { id: "MNT-441", date: "2026-04-28", type: "Pre-Trip", truckId: "TRK-4821", summary: "All checks passed", severity: null, odometer: 84010 },
  { id: "MNT-440", date: "2026-04-27", type: "Issue Report", truckId: "TRK-4821", summary: "Driver side mirror vibration at highway speed", severity: "minor", odometer: 83780 },
  { id: "MNT-439", date: "2026-04-21", type: "Post-Trip", truckId: "TRK-4821", summary: "Hose clamp on C3 valve slightly loose — flagged", severity: "needs_attention", odometer: 83410 },
];