/**
 * FuelRouteOS — Tenant Branding Config
 *
 * This is the single source of truth for tenant/client branding.
 * In production, this object would be fetched from the TenantBranding entity
 * based on the authenticated user's tenantId.
 *
 * Future entity schema:
 * {
 *   tenantId, companyDisplayName, companyLegalName,
 *   logoUrl, iconUrl, accentColor,
 *   dispatchPhone, supportPhone, supportEmail, billingEmail,
 *   website, address, documentFooterText, showPoweredBy,
 *   createdAt, updatedAt
 * }
 */

export const tenantBranding = {
  platformName: "FuelRouteOS",
  platformProductName: "FuelRouteOS Driver",
  platformSubtitle: "Driver Portal",
  poweredBy: "Sentinels FleetOps",

  tenantId: "demo-carrier",
  companyDisplayName: "Sentinels FleetOps Demo Carrier",
  companyLegalName: "Sentinels FleetOps Demo Carrier LLC",

  logoUrl: null,
  logoAlt: "Sentinels FleetOps Demo Carrier",
  iconUrl: null,

  accentColor: "#2563EB",

  dispatchPhone: "+1 (832) 755-6477",
  supportPhone: "+1 (832) 755-6477",
  supportEmail: "support@fuelrouteos.demo",
  billingEmail: "billing@fuelrouteos.demo",
  website: "https://fuelrouteos.com",

  companyAddress: {
    line1: "Demo Address",
    city: "Houston",
    state: "TX",
    postalCode: "77000",
    country: "USA",
  },

  documentBranding: {
    showLogo: true,
    showPoweredBy: true,
    footerText: "Generated by FuelRouteOS",
    receiptFooter: "Delivery record generated through FuelRouteOS.",
    reportFooter: "FuelRouteOS Driver Operations Report",
  },

  legal: {
    termsUrl: "/terms",
    privacyUrl: "/privacy",
    accessibilityUrl: "/accessibility-statement",
    dataUseUrl: "/data-use",
  },
};

export default tenantBranding;